spring:
  data:
    mongodb:
      authentication-database: none
      database: account
      port: '27017'
      host: localhost
server:
  port: '8002'
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost