spring:
  data:
    mongodb:
      authentication-database: none
      database: credit
      port: '27017'
      host: localhost
server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}