spring:
  data:
    mongodb:
      authentication-database: none
      database: customer
      port: '27017'
      host: localhost
server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j.circuitbreaker:
    instances:
        serviceCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 20
            waitDurationInOpenState: 15s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10